# Generated by Django 5.2.7 on 2025-11-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='Employee Number')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('roles', models.JSONField(default=list, verbose_name='Roles')),
            ],
            options={
                'verbose_name': 'Master Employee',
                'verbose_name_plural': 'Master Employees',
                'ordering': ['employee_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.masteremployee', verbose_name='Employee'),
        ),
        migrations.DeleteModel(
            name='EmployeeMaster',
        ),
    ]
