# Generated by Django 5.2.7 on 2025-11-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useraccount_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterEmployee',
        ),
    ]
