# Generated by Django 5.2.7 on 2025-11-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_useraccount_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={},
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('roles', models.ManyToManyField(to='authentication.role')),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.staff'),
        ),
    ]
