# Generated by Django 5.2.7 on 2025-11-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_role_alter_useraccount_options_staff_and_more'),
        ('users', '0014_alter_staff_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='roles',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.staff', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
