# Generated by Django 5.2.7 on 2025-11-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_staff_roles_alter_useraccount_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.rolelist')),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.staff', verbose_name='Employee'),
        ),
    ]
