# Generated by Django 5.2.7 on 2026-04-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanboard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_roadmaps', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='users.staff'),
        ),
    ]
