# Generated by Django 5.2.7 on 2026-04-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_auditlog'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        # Personal Board
        migrations.CreateModel(
            name='PersonalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Tasks', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_boards', to='users.staff')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        
        # Personal Column
        migrations.CreateModel(
            name='PersonalColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6b7280', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='task_management.personalboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        
        # Personal Task
        migrations.CreateModel(
            name='PersonalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('recurring_days', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.personalboard')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_management.personalcolumn')),
            ],
            options={
                'ordering': ['column__order', 'order'],
            },
        ),
        
        # Task Checklist Item
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='task_management.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        
        # Task Comment
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_note', models.BooleanField(default=False, help_text='If True, this is a note instead of a comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='users.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_management.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        
        # Add unique_together constraints
        migrations.AddConstraint(
            model_name='personalboard',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_board_name'),
        ),
        migrations.AddConstraint(
            model_name='personalcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_board_column_name'),
        ),
    ]