# Generated by Django 5.2.7 on 2026-04-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_personal_and_task_enhancements'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personalboard',
            name='unique_user_board_name',
        ),
        migrations.RemoveConstraint(
            model_name='personalcolumn',
            name='unique_board_column_name',
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskchecklistitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='personalboard',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='personalcolumn',
            unique_together={('board', 'name')},
        ),
    ]
