# Generated by Django 5.2.7 on 2026-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_personaltaskchecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
