# Generated by Django 5.2.7 on 2026-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_personaltask_date_end_personaltask_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalboard',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalboard',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
