# Generated by Django 5.2.7 on 2026-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_personalboard_archived_at_personalboard_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
