# Generated by Django 5.2.7 on 2026-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0009_add_personal_task_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
