# Generated by Django 5.2.7 on 2026-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0010_personaltask_deadline_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalboard',
            options={'ordering': ['order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='personalboard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
