# Generated by Django 5.2.7 on 2026-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_alter_personalboard_options_personalboard_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalboard',
            name='tag',
            field=models.CharField(blank=True, choices=[('work', 'Work Projects'), ('personal', 'Personal Growth'), ('health', 'Health & Fitness'), ('finance', 'Finance & Money'), ('learning', 'Learning & Skills'), ('home', 'Home & Family'), ('hobby', 'Hobbies & Fun'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
