# Generated by Django 5.2.7 on 2026-05-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0012_personalboard_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalboard',
            name='accent_color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AddField(
            model_name='personalboard',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_backgrounds/'),
        ),
        migrations.AddField(
            model_name='personalboard',
            name='background_pattern',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='personalboard',
            name='theme_preset',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('ocean', 'Ocean'), ('sunset', 'Sunset'), ('forest', 'Forest')], default='default', max_length=30),
        ),
    ]
