# Generated by Django 5.2.7 on 2025-11-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_alter_staff_middle_name_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
