# Generated by Django 5.2.7 on 2025-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_name_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('top_management', 'Top Management'), ('compliance', 'Compliance'), ('sales_and_marketing', 'Sales and Marketing'), ('sales_operation_processes', 'Sales Operations Processes'), ('finance', 'Finance'), ('human_resource', 'Human Resource'), ('marketing', 'Marketing'), ('sales_production', 'Sales Production'), ('client_success_management', 'Client Success Management'), ('administrative', 'Administrative'), ('design_and_technical', 'Design and Technical')], max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift'), ('flexible', 'Flexible / Others')], max_length=20),
        ),
    ]
