# Generated by Django 5.2.7 on 2025-11-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_staff_department_alter_staff_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rank',
            field=models.CharField(blank=True, choices=[('rank_and_file', 'Rank and File'), ('supervisory', 'Supervisory'), ('managerial', 'Managerial'), ('director', 'Director'), ('top-management', 'Top Management')], max_length=20, null=True),
        ),
    ]
