# Generated by Django 5.2.7 on 2025-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staff_age_staff_birthdate_staff_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tenure_active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
