# Generated by Django 5.2.7 on 2025-11-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_staff_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='Master_Employee',
        ),
    ]
