# Generated by Django 5.2.7 on 2025-11-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_staff_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
    ]
