# Generated by Django 5.2.7 on 2025-11-21 11:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_alter_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift'), ('flexible', 'Flexible / Others')], max_length=20)),
                ('rank', models.CharField(choices=[('rank_and_file', 'Rank and File'), ('supervisory', 'Supervisory'), ('managerial', 'Managerial'), ('director', 'Director'), ('top-management', 'Top Management')], max_length=20)),
                ('clock_in_start', models.TimeField()),
                ('clock_in_end', models.TimeField()),
                ('clock_out', models.TimeField()),
            ],
            options={
                'db_table': 'human_resource_employeeshiftrule',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, choices=[('rank_and_file', 'Rank and File'), ('supervisory', 'Supervisory'), ('managerial', 'Managerial'), ('director', 'Director'), ('top-management', 'Top Management')], max_length=20, null=True)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift'), ('flexible', 'Flexible / Others')], max_length=20, null=True)),
                ('initial_vl', models.IntegerField(default=6)),
                ('initial_sl', models.IntegerField(default=6)),
                ('current_vl', models.IntegerField(default=6)),
                ('current_sl', models.IntegerField(default=6)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
    ]
