# Generated by Django 5.2.7 on 2025-11-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_remove_attendance_note_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshiftrule',
            name='rank',
            field=models.CharField(choices=[('rank_and_file', 'Rank and File'), ('supervisory', 'Supervisory'), ('managerial', 'Managerial'), ('director', 'Director'), ('top-management', 'Top Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeshiftrule',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift'), ('flexible', 'Flexible / Others')], max_length=50),
        ),
    ]
