# Generated by Django 5.2.7 on 2025-11-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_alter_employeeshiftrule_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=50),
        ),
    ]
