# Generated by Django 5.2.7 on 2025-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0010_leaverequest_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='paid',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
