# Generated by Django 5.2.7 on 2025-11-24 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0013_remove_leaverequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='date_filed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
