# Generated by Django 5.2.7 on 2025-11-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0015_remove_leaverequest_designation_and_more'),
        ('users', '0015_alter_staff_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavecredit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavecredit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavecredit',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='leavecredit',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
