# Generated by Django 5.2.7 on 2025-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0016_alter_leavecredit_unique_together_leavecredit_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day',
            field=models.BooleanField(default=False),
        ),
    ]
