# Generated by Django 5.2.7 on 2025-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0017_leaverequest_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecredit',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavecredit',
            name='used',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
