# Generated by Django 5.2.7 on 2025-11-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rolelist_staff_alter_useraccount_employee'),
        ('users', '0014_alter_staff_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.staff', verbose_name='Employee'),
        ),
        migrations.DeleteModel(
            name='RoleList',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]

