# Generated by Django 5.2.7 on 2026-02-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_staff_role_alter_useraccount_employee_and_more'),
        ('users', '0023_remove_role_created_at_remove_role_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, max_length=50)),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Browser')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('failure_reason', models.CharField(blank=True, max_length=100, verbose_name='Failure Reason')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
            options={
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-login_time'],
            },
        ),
    ]

