# Generated by Django 5.2.7 on 2026-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]

