# Generated by Django 5.2.7 on 2025-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('job_title', models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('hr_manager', 'HR Manager'), ('auditor', 'Auditor'), ('sales_rep', 'Sales Rep'), ('designer', 'Designer')], max_length=50)),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('probationary', 'Probationary'), ('contractual', 'Contractual'), ('consultant', 'Consultant'), ('part_time', 'Part time'), ('freelance', 'Freelance'), ('defined', 'Defined')], max_length=20)),
                ('department', models.CharField(choices=[('top_management', 'Top Management'), ('rank_and_file', 'Rank and File'), ('compliance', 'Compliance')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]

