# Generated by Django 5.2.7 on 2025-11-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift'), ('flexible', 'Flexible / Others')], default='morning', max_length=20),
        ),
    ]

