# Generated by Django 5.2.7 on 2025-11-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_role_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
    ]

