# Generated by Django 5.2.7 on 2025-11-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_staff_tenure_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='Master_Employee',
        ),
    ]

