# Generated by Django 5.2.7 on 2026-02-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_role_created_at_role_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
    ]

