# Generated by Django 5.2.7 on 2026-02-20 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_role_created_at_remove_role_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('job_title', 'Job Title'), ('type', 'Employment Type'), ('department', 'Department'), ('rank', 'Rank'), ('shift', 'Shift'), ('positionlink', 'Position'), ('role', 'Role'), ('status', 'Status'), ('first_name', 'First Name'), ('middle_name', 'Middle Name'), ('last_name', 'Last Name'), ('birthdate', 'Birthdate'), ('age', 'Age'), ('sex', 'Sex'), ('start_date', 'Start Date'), ('employee_number', 'Employee Number'), ('sss_number', 'SSS Number'), ('pagibig_number', 'Pag-IBIG Number'), ('philhealth_number', 'PhilHealth Number'), ('email_address', 'Email Address'), ('phone_number', 'Phone Number'), ('emergency_contact_name', 'Emergency Contact Name'), ('emergency_contact_number', 'Emergency Contact Number')], max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_changes_made', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='users.staff')),
            ],
            options={
                'verbose_name': 'Staff History',
                'verbose_name_plural': 'Staff History Records',
                'ordering': ['-changed_at'],
            },
        ),
    ]

