# Generated by Django 5.2.7 on 2026-02-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_staffhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_changes_made', to='users.staff'),
        ),
        migrations.AlterField(
            model_name='staffhistory',
            name='field_name',
            field=models.CharField(choices=[('job_title', 'Job Title'), ('type', 'Employment Type'), ('department', 'Department'), ('departmentlink', 'Department Link'), ('rank', 'Rank'), ('shift', 'Shift'), ('positionlink', 'Position'), ('role', 'Role'), ('status', 'Status'), ('first_name', 'First Name'), ('middle_name', 'Middle Name'), ('last_name', 'Last Name'), ('birthdate', 'Birthdate'), ('age', 'Age'), ('sex', 'Sex'), ('start_date', 'Start Date'), ('tenure_active', 'Tenure'), ('employee_number', 'Employee Number'), ('sss_number', 'SSS Number'), ('pagibig_number', 'Pag-IBIG Number'), ('philhealth_number', 'PhilHealth Number'), ('email_address', 'Email Address'), ('phone_number', 'Phone Number'), ('emergency_contact_name', 'Emergency Contact Name'), ('emergency_contact_number', 'Emergency Contact Number')], max_length=50),
        ),
    ]

