# Generated by Django 5.2.7 on 2026-03-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_staffhistory_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffhistory',
            name='field_name',
            field=models.CharField(choices=[('job_title', 'Job Title'), ('type', 'Employment Type'), ('department', 'Department'), ('departmentlink', 'Department Link'), ('rank', 'Rank'), ('shift', 'Shift'), ('positionlink', 'Position'), ('role', 'Role'), ('status', 'Status'), ('first_name', 'First Name'), ('middle_name', 'Middle Name'), ('last_name', 'Last Name'), ('birthdate', 'Birthdate'), ('age', 'Age'), ('sex', 'Sex'), ('start_date', 'Start Date'), ('tenure_active', 'Tenure'), ('employee_number', 'Employee Number'), ('sss_number', 'SSS Number'), ('pagibig_number', 'Pag-IBIG Number'), ('philhealth_number', 'PhilHealth Number'), ('email_address', 'Email Address'), ('phone_number', 'Phone Number'), ('emergency_contact_name', 'Emergency Contact Name'), ('emergency_contact_number', 'Emergency Contact Number'), ('street_address', 'Street Address'), ('city', 'City'), ('province', 'Province'), ('postal_code', 'Postal Code'), ('country', 'Country')], max_length=50),
        ),
    ]

