# Generated by Django 5.2.7 on 2026-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_staff_city_staff_country_staff_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='pagibig_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='philhealth_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='sss_number',
        ),
        migrations.AlterField(
            model_name='staffhistory',
            name='field_name',
            field=models.CharField(choices=[('job_title', 'Job Title'), ('type', 'Employment Type'), ('department', 'Department'), ('departmentlink', 'Department Link'), ('rank', 'Rank'), ('shift', 'Shift'), ('positionlink', 'Position'), ('role', 'Role'), ('status', 'Status'), ('first_name', 'First Name'), ('middle_name', 'Middle Name'), ('last_name', 'Last Name'), ('birthdate', 'Birthdate'), ('age', 'Age'), ('sex', 'Sex'), ('start_date', 'Start Date'), ('tenure_active', 'Tenure'), ('employee_number', 'Employee Number'), ('email_address', 'Email Address'), ('phone_number', 'Phone Number'), ('emergency_contact_name', 'Emergency Contact Name'), ('emergency_contact_number', 'Emergency Contact Number'), ('street_address', 'Street Address'), ('city', 'City'), ('province', 'Province'), ('postal_code', 'Postal Code'), ('country', 'Country')], max_length=50),
        ),
    ]

