# Generated by Django 5.2.7 on 2025-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeshiftrule',
            options={'ordering': ['shift', 'rank']},
        ),
        migrations.AlterField(
            model_name='employeeshiftrule',
            name='clock_in_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshiftrule',
            name='clock_in_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshiftrule',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employeeshiftrule',
            unique_together={('shift', 'rank')},
        ),
    ]

