# Generated by Django 5.2.7 on 2025-11-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_alter_attendance_options_attendance_note_and_more'),
        ('users', '0015_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='note',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vl', 'Vacation Leave'), ('sl', 'Sick Leave')], max_length=2)),
                ('total', models.PositiveIntegerField(default=0)),
                ('used', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]

