# Generated by Django 5.2.7 on 2025-11-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0007_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='purpose',
            field=models.TextField(default='No purpose provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.PositiveIntegerField(),
        ),
    ]

