# Generated by Django 5.2.7 on 2025-11-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0008_alter_leaverequest_purpose_alter_leaverequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='purpose',
            field=models.TextField(default='No purpose provided'),
        ),
    ]

