# Generated by Django 5.2.7 on 2025-11-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0009_alter_leaverequest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]

