# Generated by Django 5.2.7 on 2025-11-24 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0012_leaverequest_created_at_leaverequest_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='date_filed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

