# Generated by Django 5.2.7 on 2025-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0014_leaverequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='designation',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]

