# Generated by Django 5.2.7 on 2025-11-26 19:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0019_banktype_benefit_bankallocation_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed hours worked per shift', max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes late beyond grace period'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='nsd_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Night Shift Differential hours', max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime hours', max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeshiftrule',
            name='flexible',
            field=models.BooleanField(default=False, help_text='Flexible schedule?'),
        ),
        migrations.AddField(
            model_name='employeeshiftrule',
            name='late_grace_period',
            field=models.PositiveIntegerField(default=0, help_text='Grace period in minutes'),
        ),
        migrations.AddField(
            model_name='employeeshiftrule',
            name='nsd_applicable',
            field=models.BooleanField(default=False, help_text='Night Shift Differential applicable?'),
        ),
        migrations.AddField(
            model_name='employeeshiftrule',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Expected total hours per shift', max_digits=4),
        ),
    ]

