# Generated by Django 5.2.7 on 2026-02-05 20:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0020_attendance_hours_worked_attendance_late_minutes_and_more'),
        ('users', '0018_position_staff_positionlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentContributionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('SSS', 'Social Security System'), ('PHILHEALTH', 'PhilHealth'), ('PAGIBIG', 'Pag-IBIG')], max_length=20)),
                ('salary_bracket_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_bracket_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['contribution_type', 'salary_bracket_min'],
            },
        ),
        migrations.AlterField(
            model_name='leavecredit',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.CreateModel(
            name='PayoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('night_differential', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('nsd_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('working_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('late_occurrences', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sss_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('philhealth_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pagibig_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_bracket', models.CharField(blank=True, max_length=20)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='human_resource.payout')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('OVERRIDE', 'Override Applied'), ('FINALIZE', 'Finalized'), ('VOID', 'Voided')], max_length=20)),
                ('before_values', models.JSONField(blank=True, null=True)),
                ('after_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.payout')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Audit Log',
                'verbose_name_plural': 'Payroll Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PayrollOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('override_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('overridden_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='human_resource.payout')),
            ],
            options={
                'ordering': ['-overridden_at'],
            },
        ),
    ]

