# Generated by Django 5.2.7 on 2026-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0024_payoutdetail_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]

