# Generated by Django 5.2.7 on 2026-02-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0025_add_banktype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deminimistype',
            name='code',
            field=models.CharField(help_text="Unique code for identification (e.g., 'RICE', 'FOOD', 'GAS')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tierthresholdsetting',
            name='tier_name',
            field=models.CharField(choices=[('NESTING', 'Nesting'), ('TIER1', 'Tier 1'), ('TIER2', 'Tier 2'), ('TIER3', 'Tier 3'), ('TIER4', 'Tier 4'), ('TIER5', 'Tier 5')], help_text='Tier classification for salary grading', max_length=50),
        ),
    ]

