# Generated by Django 5.2.7 on 2026-02-13 15:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0026_alter_deminimistype_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetail',
            name='lodging_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lodging allowance', max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutdetail',
            name='tips_others',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tips or other additional earnings', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollpreview',
            name='lodging_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lodging allowance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollpreview',
            name='tips_others',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tips or other additional earnings', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]

