# Generated by Django 5.2.7 on 2026-02-13 17:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0027_payoutdetail_lodging_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetail',
            name='holiday_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Holiday hours worked', max_digits=6),
        ),
        migrations.AddField(
            model_name='payoutdetail',
            name='holiday_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Holiday pay', max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutdetail',
            name='incentives',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Incentive pay', max_digits=12),
        ),
    ]

