# Generated by Django 5.2.7 on 2026-02-13 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0028_add_holiday_incentives_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetail',
            name='total_de_minimis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de minimis allowance', max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutdetail',
            name='total_dynamic_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total dynamic deductions (non-government)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutdetail',
            name='total_government_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total government deductions (SSS, PhilHealth, PAG-IBIG)', max_digits=12),
        ),
    ]

