# Generated by Django 5.2.7 on 2026-02-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0029_add_demiminis_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductionentry',
            name='payout',
            field=models.ForeignKey(blank=True, help_text='Payout reference for individual payroll', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_entries', to='human_resource.payout'),
        ),
        migrations.AddField(
            model_name='deminimisentry',
            name='payout',
            field=models.ForeignKey(blank=True, help_text='Payout reference for individual payroll', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demiminis_entries', to='human_resource.payout'),
        ),
    ]

