# Generated by Django 5.2.7 on 2026-02-16 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0030_add_payout_fk_to_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetail',
            name='regular_holiday_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular holiday hours worked', max_digits=6),
        ),
        migrations.AddField(
            model_name='payoutdetail',
            name='regular_holiday_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular holiday pay (double pay)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='regular_holiday_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed regular holiday pay', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='regular_holiday_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular holiday hours worked (double pay)', max_digits=8),
        ),
        migrations.AddField(
            model_name='payrollpreview',
            name='regular_holiday_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed regular holiday pay', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollpreview',
            name='regular_holiday_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular holiday hours worked (double pay)', max_digits=8),
        ),
        migrations.AddField(
            model_name='payrollpreview',
            name='regular_holiday_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Regular holiday rate (2.00 = double pay)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='holiday_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Special holiday hours worked', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='holiday_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Special holiday pay (30% premium)', max_digits=12),
        ),
    ]

