# Generated by Django 5.2.7 on 2026-02-17 20:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0031_payoutdetail_regular_holiday_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutdetail',
            name='days_absent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='days_present',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='late_minutes',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Actual minutes late (informational)', max_digits=10, verbose_name='Late Minutes'),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='late_occurrences',
            field=models.IntegerField(default=0, help_text='Number of times late during period'),
        ),
    ]

