# Generated by Django 5.2.7 on 2026-02-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0032_alter_payoutdetail_days_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarysetting',
            name='work_schedule',
            field=models.CharField(choices=[('8H', '8 Hours'), ('9.5H', '9.5 Hours'), ('FLEX', 'Flextime')], default='9.5H', help_text='Working hour arrangement: 8H, 9.5H, or Flextime (salary-based, no hourly computation)', max_length=10),
        ),
    ]

