# Generated by Django 5.2.7 on 2026-02-18 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0033_add_work_schedule_to_salary_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdetail',
            name='late_hours_equivalent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hours charged as penalty', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='holiday_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='holiday_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='incentives',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late deduction amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='late_minutes',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Actual minutes late', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='late_occurrences',
            field=models.PositiveIntegerField(default=0, help_text='Number of times late during period'),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='leave_days_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paid leave days', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='leave_days_unpaid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unpaid leave days', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='lodging_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='regular_holiday_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='regular_holiday_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='tips_others',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='total_de_minimis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='total_dynamic_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='total_government_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payoutdetail',
            name='working_days',
            field=models.PositiveIntegerField(default=0, help_text='Total working days in cutoff period'),
        ),
    ]

