# Generated by Django 5.2.7 on 2026-02-18 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0036_add_finalized_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrecord',
            name='released',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='released_by',
        ),
        migrations.AddField(
            model_name='payout',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payouts', to=settings.AUTH_USER_MODEL),
        ),
    ]

