# Generated by Django 5.2.7 on 2026-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0037_add_released_to_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]

