# Generated by Django 5.2.7 on 2026-02-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0038_leaverequest_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftrule',
            name='clock_out_grace_period',
            field=models.PositiveIntegerField(default=60, help_text='Grace period in minutes after clock_out time before marking failed_to_clock_out'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('early_leave', 'Early Leave'), ('failed_to_clock_out', 'Failed to Clock Out')], default='absent', max_length=50),
        ),
    ]

