# Generated by Django 5.2.7 on 2026-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0039_employeeshiftrule_clock_out_grace_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, default='', help_text='HR remarks/adjustment notes'),
        ),
    ]

