# Generated by Django 5.2.7 on 2026-02-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0040_attendance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deduction_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total deduction: late + overlunch if not validated'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_in',
            field=models.TimeField(blank=True, help_text='Time employee started lunch break', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_out',
            field=models.TimeField(blank=True, help_text='Time employee ended lunch break', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overlunch_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Extra minutes beyond standard 60 min lunch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overlunch_validated',
            field=models.BooleanField(default=False, help_text='HR validated overlunch (excluded from deduction)'),
        ),
        migrations.AddField(
            model_name='employeeshiftrule',
            name='lunch_end',
            field=models.TimeField(blank=True, help_text='Standard lunch end time (default 60 min from lunch_start)', null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftrule',
            name='lunch_start',
            field=models.TimeField(blank=True, help_text='Standard lunch start time', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes late beyond clock in start'),
        ),
    ]

