# Generated by Django 5.2.7 on 2026-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0041_attendance_deduction_minutes_attendance_lunch_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftrule',
            name='lunch_required',
            field=models.BooleanField(default=True, help_text='Whether lunch clock in/out is required for this shift'),
        ),
    ]

