# Generated by Django 5.2.7 on 2026-02-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0042_add_lunch_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='statuses',
            field=models.CharField(blank=True, default='', help_text='Multiple statuses separated by comma: present,late,absent,early_leave,failed_to_clock_out', max_length=200),
        ),
    ]

