# Generated by Django 5.2.7 on 2026-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0044_add_absent_grace_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('early_leave', 'Early Leave'), ('failed_to_clock_out', 'Failed to Clock Out'), ('missing_lunch', 'Missing Lunch')], default='absent', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='statuses',
            field=models.CharField(blank=True, default='', help_text='Multiple statuses separated by comma: present,late,absent,on_leave,early_leave,failed_to_clock_out,missing_lunch', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeshiftrule',
            name='absent_grace_period',
            field=models.PositiveIntegerField(default=60, help_text='Grace period in minutes after shift end before marking absent (if no clock in)'),
        ),
    ]

