# Generated by Django 5.2.7 on 2026-03-11 17:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0045_alter_attendance_status_alter_attendance_statuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, help_text='Set when this row was auto-created from an approved leave request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='human_resource.leaverequest'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]

