# Generated by Django 5.2.7 on 2026-03-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0046_attendance_leave_request_leaverequest_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshiftrule',
            name='clock_in_end',
        ),
    ]

