# Generated by Django 5.2.7 on 2026-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0047_remove_clock_in_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductiontype',
            name='category',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('GOVERNMENT', 'Government'), ('LOAN', 'Loan/Cash Advance'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], help_text='Category for this deduction', max_length=20),
        ),
    ]

