# Generated by Django 5.2.7 on 2026-03-16 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0048_add_insurance_category'),
        ('users', '0026_staff_city_staff_country_staff_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDeductionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, help_text='Government-provided account number (e.g., SSS number, PhilHealth ID)', max_length=100, null=True)),
                ('employer_account_number', models.CharField(blank=True, help_text="Employer's account number for this deduction type", max_length=100, null=True)),
                ('has_insurance', models.BooleanField(default=False, help_text='Whether the employee has insurance coverage for this deduction type')),
                ('insurance_policy_number', models.CharField(blank=True, help_text='Insurance policy number if employee has insurance', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this deduction account is currently active')),
                ('effective_start_date', models.DateField(default=django.utils.timezone.now, help_text='First date this deduction account is effective')),
                ('effective_end_date', models.DateField(blank=True, help_text='Last date this deduction account is effective', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this deduction account', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.ForeignKey(help_text='Type of deduction (government, attendance, insurance)', on_delete=django.db.models.deletion.CASCADE, related_name='employee_accounts', to='human_resource.deductiontype')),
                ('employee', models.ForeignKey(help_text='Employee for this deduction account', on_delete=django.db.models.deletion.CASCADE, related_name='deduction_accounts', to='users.staff')),
            ],
            options={
                'verbose_name': 'Employee Deduction Account',
                'verbose_name_plural': 'Employee Deduction Accounts',
                'db_table': 'human_resource_employeendeductionaccount',
                'ordering': ['employee', 'deduction_type'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='human_resou_employe_832f22_idx'), models.Index(fields=['deduction_type', 'is_active'], name='human_resou_deducti_a8e524_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'deduction_type', 'effective_start_date'), name='unique_deduction_account_per_employee_type_date')],
            },
        ),
    ]

