# Generated by Django 5.2.7 on 2026-03-17 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0049_employeedeductionaccount'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENPSSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Survey name (e.g., Q1 2024 Survey)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Survey description')),
                ('start_date', models.DateField(help_text='Survey start date')),
                ('end_date', models.DateField(blank=True, help_text='Survey end date (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is survey currently active?')),
                ('allow_anonymous', models.BooleanField(default=True, help_text='Allow anonymous submissions?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ENPS Survey',
                'verbose_name_plural': 'ENPS Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ENPSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='NPS Score from 0-10')),
                ('category', models.CharField(choices=[('promoter', 'Promoter (9-10)'), ('passive', 'Passive (7-8)'), ('detractor', 'Detractor (0-6)')], max_length=20)),
                ('emoji_feedback', models.CharField(choices=[('😍', 'Love it!'), ('🙂', 'Good'), ('😐', 'Neutral'), ('😞', 'Disappointed'), ('💢', 'Angry')], max_length=10)),
                ('feedback_comment', models.TextField(blank=True, help_text='Optional detailed feedback')),
                ('employee_number_hash', models.CharField(blank=True, help_text='SHA256 hash of employee number for tracking', max_length=64, null=True)),
                ('email_hash', models.CharField(blank=True, help_text='SHA256 hash of email for tracking', max_length=64, null=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If true, response is fully anonymous (no tracking)')),
                ('department', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enps_responses', to='users.staff')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='human_resource.enpssurvey')),
            ],
            options={
                'verbose_name': 'ENPS Response',
                'verbose_name_plural': 'ENPS Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ENPSDepartmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('total_responses', models.IntegerField(default=0)),
                ('enps_score', models.FloatField(default=0)),
                ('promoters_count', models.IntegerField(default=0)),
                ('passives_count', models.IntegerField(default=0)),
                ('detractors_count', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('emoji_distribution', models.JSONField(default=dict)),
                ('monthly_trend', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_analytics', to='human_resource.enpssurvey')),
            ],
            options={
                'verbose_name': 'ENPS Department Analytics',
                'verbose_name_plural': 'ENPS Department Analytics',
                'unique_together': {('survey', 'department')},
            },
        ),
    ]
