# Generated by Django 5.2.7 on 2026-03-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0050_enpssurvey_enpsresponse_enpsdepartmentanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENPSSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question to ask')),
                ('question_type', models.CharField(choices=[('nps', 'NPS Score (0-10)'), ('rating_5', 'Rating (1-5 Stars)'), ('rating_3', 'Rating (1-3)'), ('text', 'Text Answer'), ('yes_no', 'Yes/No')], default='nps', help_text='Type of question', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Must this question be answered?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of question in survey')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='human_resource.enpssurvey')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ENPSQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.IntegerField(blank=True, help_text='Score for NPS (0-10), rating questions', null=True)),
                ('text_value', models.TextField(blank=True, help_text='Text answer for text questions')),
                ('boolean_value', models.BooleanField(blank=True, help_text='Yes/No answer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='human_resource.enpsresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='human_resource.enpssurveyquestion')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
            },
        ),
    ]
