# Generated by Django 5.2.7 on 2026-03-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0051_enpssurveyquestion_enpsquestionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enpssurvey',
            name='allow_anonymous',
            field=models.BooleanField(default=False, help_text='Allow anonymous submissions?'),
        ),
    ]
