# Generated by Django 5.2.7 on 2026-03-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0052_alter_enpssurvey_allow_anonymous'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=20, unique=True)),
                ('group_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group_number'],
            },
        ),
        migrations.CreateModel(
            name='ViolationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OffenseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=20)),
                ('section_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offense_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='human_resource.offensegroup')),
            ],
            options={
                'ordering': ['offense_group', 'section_number'],
                'unique_together': {('offense_group', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='OffenseClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_description', models.TextField()),
                ('default_range', models.CharField(choices=[('A', 'Range A'), ('B', 'Range B'), ('C', 'Range C'), ('D', 'Range D')], default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offense_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='human_resource.offensesection')),
            ],
            options={
                'ordering': ['offense_section', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RemedialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_code', models.CharField(choices=[('A', 'Range A'), ('B', 'Range B'), ('C', 'Range C'), ('D', 'Range D')], max_length=1)),
                ('offense_count', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=100)),
                ('action_details', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['range_code', 'offense_count'],
                'unique_together': {('range_code', 'offense_count')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('done', 'Done'), ('working', 'Working on it'), ('stuck', 'Stuck')], default='working', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_submitted', models.DateField()),
                ('type_of_incident', models.TextField()),
                ('hr_note', models.TextField(blank=True, default='')),
                ('offense_count', models.PositiveIntegerField(default=1)),
                ('remedial_action_range', models.CharField(choices=[('A', 'Range A'), ('B', 'Range B'), ('C', 'Range C'), ('D', 'Range D')], default='A', max_length=1)),
                ('da_status', models.CharField(choices=[('done', 'Done'), ('working', 'Working'), ('stuck', 'Stuck')], default='working', max_length=20)),
                ('fully_signed', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, choices=[('disciplinary_action', 'Disciplinary Action'), ('mitigated_offense', 'Mitigated Offense')], default='', max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='violations/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='users.staff')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_violations', to='users.staff')),
                ('offense_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.offenseclassification')),
                ('remedial_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.remedialaction')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.violationcategory')),
                ('violation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.violationtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
