# Generated by Django 5.2.7 on 2026-05-14 14:45

import App.human_resource.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0053_offensegroup_violationcategory_violationtype_and_more'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_status', models.CharField(choices=[('exit', 'Exit'), ('revoked', 'Revoked'), ('indefinite_leave', 'Indefinite Leave'), ('end_contract', 'End Contract')], default='exit', max_length=30)),
                ('date_filed', models.DateField(default=datetime.date.today, help_text='Date when resignation was formally submitted')),
                ('resignation_letter', models.FileField(blank=True, help_text='Scanned copy or text file of resignation letter', null=True, upload_to=App.human_resource.models.resignation_letter_upload_path)),
                ('resignation_letter_text', models.TextField(blank=True, help_text='Text content of resignation letter (if not uploaded as file)', null=True)),
                ('desired_last_day', models.DateField(blank=True, help_text="Employee's requested last working day", null=True)),
                ('approved_last_day', models.DateField(blank=True, help_text='HR-approved final working day (considering 30-day notice)', null=True)),
                ('rendering_30day_status', models.CharField(choices=[('on_process', 'On-Process'), ('completed', 'Completed'), ('on_hold', 'On-Hold'), ('immediate', 'Immediate'), ('awol', 'AWOL'), ('ordered', 'Ordered'), ('na', 'N/A')], default='na', max_length=20)),
                ('exit_interview_status', models.CharField(choices=[('on_process', 'On-Process'), ('completed', 'Completed'), ('on_hold', 'On-Hold'), ('not_necessary', 'Not Necessary'), ('ordered', 'Ordered')], default='on_process', max_length=20)),
                ('knowledge_transfer_status', models.CharField(choices=[('on_process', 'On-Process'), ('completed', 'Completed'), ('on_hold', 'On-Hold'), ('not_necessary', 'Not Necessary'), ('ordered', 'Ordered')], default='on_process', max_length=20)),
                ('asset_return_status', models.CharField(choices=[('on_process', 'On-Process'), ('completed', 'Completed'), ('on_hold', 'On-Hold')], default='on_process', max_length=20)),
                ('clearance_status', models.CharField(choices=[('on_process', 'On-Process'), ('completed', 'Completed'), ('on_hold', 'On-Hold')], default='on_process', max_length=20)),
                ('quitclaim_status', models.CharField(choices=[('on_process', 'On-Process'), ('completed', 'Completed'), ('on_hold', 'On-Hold'), ('ordered', 'Ordered')], default='on_process', max_length=20)),
                ('final_pay_status', models.CharField(choices=[('on_hold', 'On Hold'), ('released', 'Released'), ('void', 'Void')], default='on_hold', max_length=20)),
                ('nda_signed', models.BooleanField(default=False, help_text='Non-Disclosure Agreement signed')),
                ('nca_signed', models.BooleanField(default=False, help_text='Non-Compete Agreement signed')),
                ('other_attachments', models.FileField(blank=True, help_text='Additional supporting documents', null=True, upload_to=App.human_resource.models.other_attachments_upload_path)),
                ('qualitative_data', models.JSONField(blank=True, default=dict, help_text='Structured feedback: primary drivers, improvement areas, categories')),
                ('interview_notes', models.TextField(blank=True, help_text='Additional HR notes from exit interview', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='users.staff')),
            ],
            options={
                'verbose_name': 'Exit Interview',
                'verbose_name_plural': 'Exit Interviews',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'approved_last_day')},
            },
        ),
    ]
