# Generated by Django 5.2.7 on 2026-05-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0054_exitinterview'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('resignation_status', 'Resignation Status'), ('date_filed', 'Date Filed'), ('desired_last_day', 'Desired Last Day'), ('approved_last_day', 'Approved Last Day'), ('rendering_30day_status', '30-Day Rendering Status'), ('exit_interview_status', 'Exit Interview Status'), ('knowledge_transfer_status', 'Knowledge Transfer Status'), ('asset_return_status', 'Asset Return Status'), ('clearance_status', 'Clearance Status'), ('quitclaim_status', 'Quitclaim Status'), ('final_pay_status', 'Final Pay Status'), ('nda_signed', 'NDA Signed'), ('nca_signed', 'NCA Signed'), ('resignation_letter', 'Resignation Letter'), ('other_attachments', 'Other Attachments'), ('qualitative_data', 'Qualitative Data'), ('interview_notes', 'Interview Notes')], max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_interview_changes_made', to='users.staff')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='human_resource.exitinterview')),
            ],
            options={
                'verbose_name': 'Exit Interview History',
                'verbose_name_plural': 'Exit Interview History Records',
                'ordering': ['-changed_at'],
            },
        ),
    ]
