# Generated by Django 5.2.7 on 2026-05-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0055_add_exit_interview_history'),
        ('users', '0027_remove_staff_pagibig_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('my_team', 'My Team'), ('this_week', 'This Week'), ('overdue', 'Overdue'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('filter_params', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(default=False, help_text='Share this preset with other HR users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_filter_presets', to='users.staff')),
            ],
            options={
                'verbose_name': 'Exit Interview Filter Preset',
                'verbose_name_plural': 'Exit Interview Filter Presets',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExitInterviewNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('upcoming_30day', '30-day review due soon'), ('upcoming_clearance', 'Clearance deadline approaching'), ('overdue_clearance', 'Overdue clearance'), ('overdue_pay', 'Overdue final pay')], max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='human_resource.exitinterview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_notifications', to='users.staff')),
            ],
            options={
                'verbose_name': 'Exit Interview Notification',
                'verbose_name_plural': 'Exit Interview Notifications',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'interview', 'notification_type')},
            },
        ),
    ]
